### ISSUE TITLE
Felix Logging

### ISSUE THREAD

**Issue by kirankbs** [harshild/gradle-felix-plugin#17]
Plugin should support logging for bundles as per the configuration mentioned in respective gradle files.
Need to provide Levels of logging ex:- Error,Debug,info etc.
Need to provide type of logging ex:- console,file etc.

Sub projects can also have control over logging 
Ex;- 
Logging Format 
Logging Level  etc

**Comment by harshild** [comment]
Log properties supported by Felix can be used by enclosing in felix{} 
example :- 

```
felix {
    properties.testProperty = '123'
}

```

**Comment by harshild** [comment]
Refer the updated document for the issue . addressed in commit cf0465d79d87ce27d2cadb704e7e9650f5f204ee

**Comment by harshild** [comment]
marked as resolved as no response
